language: go

sudo: false
dist: trusty

go:
- 1.x
- 1.7.x
- 1.8.x
- 1.9.x
- master

before_install:
- find "${GOPATH%%:*}" -name '*.a' -delete
- rm -rf "${GOPATH%%:*}/src/golang.org"
- go get golang.org/x/tools/cover
- go get golang.org/x/tools/cmd/cover

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s "https://codecov.io/bash")
